const test = require('node:test');
const assert = require('node:assert/strict');
const {create,empty,validate} = require('../www/store');
function setup(){let disk=empty(),now='2026-09-20T15:00:00.000Z',seq=0,fail=false;const adapter={read:()=>disk,write:v=>{if(fail)throw Error('disk full');disk=structuredClone(v);}};return {store:create(adapter,()=>now,()=>String(++seq)),adapter,time:v=>now=v,fail:()=>fail=true};}
function kid(s,name='Alex',parent='Jordan'){return s.saveKid({childName:name,parentName:parent,notes:[{text:'No nuts',flagged:true}]});}
test('siblings share one beeper; it stays reserved through partial pickup and becomes reusable at final pickup',()=>{const {store:s}=setup();const a=kid(s),b=kid(s,'Taylor'),c=kid(s,'Sam');const group=s.checkIn([a.id,b.id],{pickupParent:'Jordan'});assert.equal(group.beeperNumber,1);assert.equal(s.active().length,2);s.checkOut([group.records[0].checkinId]);assert.equal(s.checkIn([c.id],{pickupParent:'Pat'}).beeperNumber,2);s.checkOut([group.records[1].checkinId]);assert.equal(s.checkIn([a.id],{pickupParent:'Jordan'}).beeperNumber,1);assert.equal(s.history().length,4);});
test('add a later sibling to an existing group without allocating a new number',()=>{const {store:s}=setup();const a=kid(s),b=kid(s,'Taylor');const g=s.checkIn([a.id],{pickupParent:'Jordan',session:'Morning'});const more=s.checkIn([b.id],{groupId:g.records[0].groupId});assert.equal(more.beeperNumber,1);assert.equal(more.pickupParent,'Jordan');assert.equal(more.records[0].session,'Morning');});
test('30 group capacity does not limit the number of children; existing groups accept more children',()=>{const {store:s}=setup();let first;for(let i=0;i<30;i++){const result=s.checkIn([kid(s,'Child '+i).id],{pickupParent:'Parent '+i});first||=result;}const extra=kid(s,'Extra');assert.throws(()=>s.checkIn([extra.id],{pickupParent:'Extra'}),/All 30/);assert.equal(s.checkIn([extra.id],{groupId:first.records[0].groupId}).beeperNumber,1);assert.equal(s.active().length,31);});
test('duplicate selection or an active child rejects the entire group and writes no partial visit',()=>{const {store:s}=setup();const a=kid(s),b=kid(s,'Taylor');assert.throws(()=>s.checkIn([a.id,a.id],{pickupParent:'Jordan'}));s.checkIn([a.id],{pickupParent:'Jordan'});assert.throws(()=>s.checkIn([b.id,a.id],{pickupParent:'Jordan'}),/already/);assert.equal(s.history().length,1);});
test('history snapshots survive edits, checkout and deleting the saved child',()=>{const {store:s}=setup();const a=kid(s);const g=s.checkIn([a.id],{pickupParent:'Jordan'});assert.throws(()=>s.deleteKid(a.id),/Check this child out/);s.saveKid({childName:'Renamed',parentName:'New parent',notes:[]},a.id);s.checkOut([g.records[0].checkinId]);s.deleteKid(a.id);assert.equal(s.kids().length,0);assert.equal(s.history()[0].childName,'Alex');assert.equal(s.history()[0].parentName,'Jordan');assert.equal(s.history()[0].notes[0].text,'No nuts');});
test('failed durable save leaves current state unchanged',()=>{const x=setup();const a=kid(x.store);x.fail();assert.throws(()=>x.store.checkIn([a.id],{pickupParent:'Jordan'}),/disk full/);assert.equal(x.store.active().length,0);assert.equal(x.store.snapshot().revision,1);});
test('reopening retains saved kids, active groups and finished history',()=>{const x=setup();const a=kid(x.store),b=kid(x.store,'Taylor');const g=x.store.checkIn([a.id,b.id],{pickupParent:'Jordan'});x.store.checkOut([g.records[0].checkinId]);const reopened=create(x.adapter);assert.equal(reopened.kids().length,2);assert.equal(reopened.active().length,1);assert.equal(reopened.history({status:'done'}).length,1);});
test('date filters include checked-out attendance and visits spanning midnight in present mode',()=>{const x=setup();const a=kid(x.store);x.time('2026-09-20T23:50:00.000Z');const g=x.store.checkIn([a.id],{pickupParent:'Jordan',session:'Evening'});x.time('2026-09-21T00:30:00.000Z');x.store.checkOut([g.records[0].checkinId]);assert.equal(x.store.history({from:'2026-09-21',to:'2026-09-21'}).length,0);assert.equal(x.store.history({from:'2026-09-21',to:'2026-09-21',mode:'present'}).length,1);assert.equal(x.store.history({search:'evening',status:'done'}).length,1);assert.throws(()=>x.store.history({from:'2026-09-22',to:'2026-09-20'}),/end date/);});
test('backup round trip and malformed restore cannot silently replace current data',()=>{const x=setup();kid(x.store);const y=setup();y.store.restore(x.store.snapshot());assert.equal(y.store.kids().length,1);const bad=x.store.snapshot();bad.kids[0].child_name=123;assert.throws(()=>y.store.restore(bad));assert.equal(y.store.kids()[0].child_name,'Alex');});
test('clock moving backwards does not corrupt checkout timestamps',()=>{const x=setup();const g=x.store.checkIn([kid(x.store).id],{pickupParent:'Jordan'});x.time('2026-09-19T00:00:00Z');assert.throws(()=>x.store.checkOut([g.records[0].checkinId]),/clock/);assert.equal(x.store.active().length,1);});
test('original database migration validates and preserves every row',()=>{const data=validate(require('../Existing-Data-Backup.json'));assert.equal(data.kids.length,7);assert.equal(data.checkins.length,15);});
