const assert = require('node:assert/strict');
const path = require('node:path');
const {pathToFileURL} = require('node:url');
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--no-sandbox']});
 const context=await browser.newContext({viewport:{width:600,height:960},timezoneId:'America/Boise',acceptDownloads:true});
 const page=await context.newPage(),errors=[],network=[];
 page.on('pageerror',e=>errors.push(e.message));
 page.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url());});
 const url=pathToFileURL(path.resolve(__dirname,'../www/index.html')).href;
 await page.goto(url);
 await context.setOffline(true);
 await page.getByRole('button',{name:'Check In',exact:true}).click();
 async function add(name){
  await page.getByRole('button',{name:'+ Add New Kid',exact:true}).click();
  await page.getByLabel("Child's Name",{exact:true}).fill(name);
  await page.getByLabel("Parent's Name",{exact:true}).fill('Jordan Parent');
  if(name==='Alex Example'){
   await page.getByRole('button',{name:'+ Add Note'}).click();
   await page.getByPlaceholder('e.g. Severe nut allergy').fill('Nut allergy');
   await page.getByLabel('Flag on Hub').check();
  }
  await page.getByRole('button',{name:'Save & Select',exact:true}).click();
 }
 assert.equal(await page.locator('#groupChoice, #sessionName').count(),0);
 await add('Alex Example'); await add('Taylor Example'); await add('Jamie Example');
 await page.getByRole('button',{name:'Check In (3)',exact:true}).click();
 assert.equal(await page.getByRole('dialog',{name:'Check-in complete',exact:true}).count(),1);
 assert.equal(await page.locator('#pickupParent, #saveGroup').count(),0);
 await page.getByRole('button',{name:'Done',exact:true}).click();
 let visits=await page.evaluate(()=>store.active());
 assert.equal(visits.length,3);assert.equal(visits[0].beeperNumber,visits[1].beeperNumber);
 await page.getByRole('button',{name:'Hub',exact:true}).click();
 assert.equal(await page.locator('.hub-grid').count(),1);
 assert.equal(await page.locator('.family-group').count(),0);
 assert.equal(await page.locator('.kid-card').count(),3);
 assert.match(await page.locator('.alert-banner').innerText(),/Nut allergy/);
 await page.screenshot({path:path.resolve(__dirname,'../../qa-hub-portrait.png'),fullPage:true});
 await page.setViewportSize({width:1024,height:600});
 await page.screenshot({path:path.resolve(__dirname,'../../qa-hub-landscape.png'),fullPage:true});
 await page.getByRole('button',{name:'Check Out',exact:true}).first().click();
 await page.locator('#acceptConfirm').click();
 assert.equal(await page.locator('.kid-card').count(),2);
 await page.reload();
 assert.equal(await page.locator('.kid-card').count(),2);
 await page.getByRole('button',{name:'Check out group #1',exact:true}).first().click();
 await page.locator('#acceptConfirm').click();
 assert.equal(await page.locator('.kid-card').count(),0);
 await page.getByRole('button',{name:'Manage Kids',exact:true}).click();
 await page.locator('.roster-row').filter({hasText:'Alex Example'}).getByRole('button',{name:'Edit',exact:true}).click();
 await page.getByLabel("Child's Name",{exact:true}).fill('Alex Renamed');
 await page.getByRole('button',{name:'Save',exact:true}).click();
 await page.locator('.roster-row').filter({hasText:'Alex Renamed'}).getByRole('button',{name:'Delete',exact:true}).click();
 await page.locator('#acceptConfirm').click();
 await page.getByRole('button',{name:'Check-In History',exact:true}).click();
 assert.equal(await page.locator('tbody tr').count(),3);
 assert.match(await page.locator('tbody').innerText(),/Alex Example/);
 await page.getByRole('searchbox',{name:'Search attendance history'}).fill('Taylor');
 assert.equal(await page.locator('tbody tr').count(),1);
 await page.getByRole('searchbox',{name:'Search attendance history'}).fill('');
 await page.screenshot({path:path.resolve(__dirname,'../../qa-history.png'),fullPage:true});
 const popupPromise=page.waitForEvent('popup');
 await page.getByRole('button',{name:'Print / Save PDF',exact:true}).click();
 const report=await popupPromise;await report.waitForLoadState();
 assert.equal(await report.locator('tbody tr').count(),3);
 assert.match(await report.locator('h1').innerText(),/Children Check In/);
 await report.pdf({path:path.resolve(__dirname,'../../qa-report.pdf'),printBackground:true,preferCSSPageSize:true});
 await report.close();
 let downloadPromise=page.waitForEvent('download');
 await page.getByRole('button',{name:'Export CSV',exact:true}).click();
 let download=await downloadPromise;await download.saveAs(path.resolve(__dirname,'../../qa-attendance.csv'));
 await page.getByRole('button',{name:'Manage Kids',exact:true}).click();
 downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Save backup',exact:true}).click();
 download=await downloadPromise;const backupPath=path.resolve(__dirname,'../../qa-backup.json');await download.saveAs(backupPath);
 await page.locator('#restoreFile').setInputFiles(backupPath);
 await page.locator('#acceptConfirm').click();
 assert.equal((await page.evaluate(()=>store.history())).length,3);
 await page.setViewportSize({width:360,height:640});
 for(const name of ['Hub','Check In','Manage Kids','Check-In History']){
  await page.getByRole('button',{name,exact:true}).click();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'No page overflow: '+name);
 }
 assert.deepEqual(errors,[]);assert.deepEqual(network,[]);
 await page.close();
 const reopened=await context.newPage();await reopened.goto(url);assert.equal((await reopened.evaluate(()=>store.history())).length,3);
 console.log('PASS: offline UI, direct group check-in, removed options/prompt, compact Hub, partial/group checkout, reload persistence, immutable history, search, print report, CSV, backup/restore, small-screen layout.');
 console.log('PASS: zero HTTP requests and zero JavaScript errors.');
 await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
